docs/cli.md

Ref: https://github.com/verdaccio/verdaccio/issues/1141

fix: fixes XDG_CONFIG_HOME in cli docs

---

website/pages/en/users.js

This PR will fix link "ADD YOUR COMPANY" on page https://verdaccio.org/en/users.html

fix link to siteConfig.js

---

docs/iis-server.md

Fix: 19: Updated start.js for v3.0+

---

docs/amazon.md

Requires https://github.com/verdaccio/verdaccio/pull/1254 to be merged first

Add docs for AWS deployment

---

docs/install.md

Hey @juanpicado here is the change that I made to the docs, and this is how it looks after render
Please let me know if any changes or words that need to be changed :)

Added npm-set registry command to installation file

---

docs/web.md

https://github.com/verdaccio/verdaccio/pull/1278

docs: add an example that uses a local file for the logo

---

website/blog/2019-05-13-the-new-docker-image-verdaccio-4.md

What's new in Verdaccio 4 (Docker Image)
This is just small article that will be part of the V4 release.

feat: add docker verdaccio 4 release blog

---

docs/ci.md

chore(ci): improve language

---

docs/articles.md

* Used title case for consistency with other headings.
* Some grammar and language changes to make reading more natural and friendly.

chore(articles): use title casing and improve language

---

docs/web.md

fix: the <br> in the table will break other languages page

---

docs/cli.md

Related to PR https://github.com/verdaccio/verdaccio/pull/1258.

feat: CLI config file formats

---

docs/caching.md

Fix spelling mistake

---

website/pages/en/index.js

Set the data-lang attribute based on the localization.

Localize tweets

---

website/siteConfig.js

Fixes https://github.com/verdaccio/website/issues/178

Fix version links

---

website/pages/en/versions.js

Fixes #178 - but, this time, might not break the build ...

Fix version links (#180) - again

---

docs/who-is-using.md

At [Satispay](https://www.satispay.com) we use Verdaccio for all our private packages 🎉

Add Satispay in who is using section

---

website/blog/2019-05-13-the-new-docker-image-verdaccio-4.md

My name is Kopriwa, it means nettle, thanks for the contribution note.

fix(contributions): Updated a wrong family name

---

docs/reverse-proxy.md

Hi, Thanks for your project.
I have set a quick fix for the apache2 reverse proxy.
Without that it cant work correctly if you choose the https way.

Add Forwarded-Proto missing headers

---

website/data/team.yml

This PR fixes a small typo in my name =)

docs(website): fix small typo

---

website/versioned_docs/version-3.8.6/docker.md
website/versioned_docs/version-4.0.0-alpha.4/docker.md
website/versioned_docs/version-4.0.0-alpha.5/docker.md
website/versioned_docs/version-4.0.0-beta.5/docker.md
website/versioned_docs/version-4.0.0-beta.8/docker.md
website/versioned_docs/version-4.0.0/docker.md
website/versioned_docs/version-4.0.1/docker.md

This PR should resolve the mixed content warnings. But we also have to update the translated docs.

docs(website): resolve mixed content

---

README.md

Made the contributing section point to the respective file.

[Docs]: Add reference to the contributing guide

---

README.md

Made the license badge point to the respective file.

[Docs]: update badge reference

---

docs/dev-plugins.md
docs/plugin-auth.md
docs/plugin-generator.md
docs/plugin-middleware.md
docs/plugin-storage.md
docs/plugins.md
website/i18n/en.json
website/sidebars.json

- add info about the new plugin generator
- add detailed info about each type of plugin (new pages for each)
- sidebar new navigation
- remove flow notes (old stuff)
🙃 I'm sure tons of typos are around.

docs: add plugin generator info

---

docs/reverse-proxy.md

Adding config while installing Verdaccio on the root directory as current config fails in that scenario.

Add configuration of the apache reverse proxy

---

docs/install.md

This PR updates the docs according to https://github.com/verdaccio/verdaccio/blob/c30412b6db0a7b267a57a171173ed13c6a84e30a/package.json#L137

docs: update npm and pnpm version

---

docs/articles.md

Written 4 parts article series about how to setup Verdaccio with SSL and Docker

Add German article

---

docs/e2e.md

chore(e2e): fixed grammar err

---

docs/auth.md

- max_users does not restrict login, it restricts registration, probably an oversight.
- improve grammar and punctuations

docs: fix incorrect statement plus grammar

---

docs/plugin-middleware.md

Fix the verdaccio-audit plugin link.

fix: update link to the verdaccio-audit plugin

---

docs/best-practices.md

Found some improvable lines and took action.
Fixed some typos and minor grammatical errors. 🤓
Issue #277

docs(web): Fixed typos for best-practices documentation

---

README.md

Updated local install instructions to use pnpm instead of yarn.

doc: Updating local install instructions to use pnpm.

---

docs/install.md
docs/what-is-verdaccio.md

Found some improvements in the **installation docs**. Simple stuff.

doc: Improved install documentation

---

docs/auth.md
docs/plugins.md
website/sidebars.json

* authentification -> authentication
* few spelling mistakes in plugins.md

Few documentation fixes

---

docs/kubernetes.md

Based on the request here: https://github.com/verdaccio/verdaccio/issues/1463

Add info on NGINX proxy body-size limit

---

docs/articles.md

Having a code versioned according to SemVer standards can simplify everyone’s life. This post shows you how to automate package publishing using some helpful tools and best practices.

docs: new article on how to automate package publishing in JavaScript projects

---

docs/best-practices.md

Added a new resource for reading to prevent dependency confusion attack

update security recommendations
