verdaccio/website

docs/web.md
- https://github.com/verdaccio/ui/pull/36
- https://github.com/verdaccio/verdaccio/pull/1282
=> docs: add primary_color config option to web.md

docs/uplinks.md
I think there are more than just two properties for the uplinks configuration.
=> docs(uplinks): change text before properties table

docs/repositories.md, website/versioned_docs/version-3.8.6/test.md
There ins an [issue in Docusaurus](https://github.com/facebook/Docusaurus/issues/845) which breaks old documentations if the files which are used / referenced there are removed in `next` / current `docs`.
This PR provides a workaround to fix the v3 docs.
=> fix: add empty pages to prevent missing files during generation of v3 docs

docs/docker.md
There is an image which is loaded through `http` instead of `https` and throws a mixed content warning in environments (build, deployment, website).
=> fix: use https to prevent mixed content warnings

docs/web.md
Since v4 escaping of the scope is not needed anymore.
=> docs: fix scope example for the web UI config (fixes #133)

docs/kubernetes.md
The `full.yaml` file no longer contains any configuration. This PR updates the Kubernetes docs to reference the `docker.yaml` file instead.
=> reference docker.yaml instead of full.yaml

.dockerignore, Dockerfile, README.md
Added Docker support - The site can now be launched as a docker container:
* dockerfile & dockerignore are added
* readme changes, update for running as a container information
* running as a container provides offline support for Verdaccio docs site
=> docs(website): Docker support for website

docs/cli.md
[#1365](https://github.com/verdaccio/verdaccio/pull/1365) brings about a new `--info` option which prints useful information concerning the local environment.
=> Update docs to include --info

Dockerfile
At the moment of writing this PR, the sizes of Node images are:
- **node:lts** -> _904MB_
- **node:lts-slim** -> _148MB_
- **node:lts-alpine** -> _75.3MB_
Currently, we are using **node:lts** for running the website in a local dev environment (or as local docs), but the base image size is really big for users that don't have a high speed connections (and it's a metered connections killer).
I want to migrate to **node:lts-alpine** as is the smaller one, but we have to install some utilities needed to install project dependencies that don't come with the base image but **node:lts-slim** base image contains.
Comparing the best two options, **slim vs alpine**, the size of the image generated with **node:lts-alpine** base image is _243MB_, and **node:lts-slim** is _293MB_, so we can try using …
=> chore: use node alpine image to reduce size in local development

docs/reverse-proxy.md
Apache 2.4.39 reverse proxy virtual host configuration fails if ProxyPass{Reverse}'s `url` parameter is missing the trailing slash.
=> reverse-proxy.md: Apache example ProxyPass{Reverse} directive missing trailing slash

docs/uplinks.md
Adds doc for `agent_options` uplink configuration setting See the following for more details:
Issue: https://github.com/verdaccio/verdaccio/issues/1329
PR: https://github.com/verdaccio/verdaccio/pull/1332
=> feat: add agent_options to uplink configuration doc

docs/docker.md
Updated command in docker.md! Let me know if any other changes are needed
References this issue: https://github.com/verdaccio/website/issues/132
=> Chore: updated chown command in docker.md

docs/who-is-using.md
**Type:** Refactor
**The following has been addressed in the PR:** there is no issue
**Description:**
Apollo GraphQL now uses Verdaccio 👏😀 So I have added this information in the section "Who is using verdaccio"
=> updated readme: Added Apollo GraphQL 

docs/docker.md
The VERDACCIO_APPDIR is `/opt/verdaccio`, see https://github.com/verdaccio/verdaccio/blob/287ed3f88c899411839cdbea3e41ca10b528ca97/Dockerfile#L27
=> docs(website): use the correct working directory path

docs/reverse-proxy.md
This PR fixes a small typo in the readme. It should be `relative`.
=> docs: fix small typo

docs/packages.md
This adds documentation on how to use multiple uplinks as a proxy, and describes some of the use cases.
cc @juanpicado
=> Add documentation on multiple uplinks to proxy

docs/docker.md
Hello, I've recenly setup a repository to auto build multiarch docker images of verdaccio using buildx and thought the documentation would find it useful.
Currently the images are buildt only for `amd64`  arch and can not be run on Raspberry Pi (`arm`), this repository adds support for multiarch images which include `arm` builds.
=> Add link to hertzg/docker-verdaccio-multiarch

docs/web.md
Saw a typo for `darMode` while browsing the docs [here](https://verdaccio.org/docs/en/webui). Updating typo. Also fixes `enabled` typo
=> docs(web): fixes a few typos

docs/plugins.md
Changed `This is tecnically possible, making the plugin order important, as the credentials will be resolved in order.` to `This is technically possible, making the plugin order important, as the credentials will be resolved in order.` :)
=> Fixed typo for plugins documentation

docs/best-practices.md
Typo on command:
```
npm publish --tag fix --registry http://localhost:4873
```
=> Typo on `docs/best-practices.md`

docs/docker.md
When I copied this command from docs and ran a verdaccio instance first time, I got confused that how to ran it in an unblock way.
Since I was not so familiar with docker commands, so I spent some time to work it out. 
Hope this small change could help others who are in the same situation.
=> docs: and docker run with -d note

docs/docker.md
fixes #218 
Currently the Docker instructions mention `sudo chown -R 10001:65533 /opt/verdaccio` but this would have to be done in the container while it is running.
It should be `sudo chown -R 10001:65533 /path/for/verdaccio` in this case.
https://verdaccio.org/docs/en/docker.html
=> docker doc fix

docs/kubernetes.md
The following helm commands are not valid with `helm 3`.
The changes were tested on:
`version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
`
=> doc:correct helm commands

docs/auth.md, docs/best-practices.md, docs/cli-registry.md, docs/cli.md, docs/config.md, docs/how-to-deploy-on-AWS.md, docs/logger.md, docs/node-api.md, docs/notifications.md, docs/packages.md, docs/plugin-auth.md, docs/protect-your-dependencies.md, docs/reverse-proxy.md, docs/server.md, docs/ssl.md, docs/web.md
Hi all,
I'm not sure if purely grammar and spelling fixes are frowned upon here, but I wanted to amend and fix up some of the wording to make the documentation clearer and flow better.
The following pages have received changes:
* Command Line Tool
* Using a private registry
* Configuration File
* Packages
* Authentication
* Notifications
* Best Practices
* Protecting packages
* Amazon Web Services
* Reverse Proxy Setup
* Set up the SSL Certificates
* Authentication Plugin
* Node API
Most of the changes are simple grammar or spelling fixes, but I have reworded whole sentences in certain places to be more readable. I have not changed the meaning behind any of the wording, just how they're written.
Thanks for the awesome tool!
=> Documentation grammar, clarity and spelling fixes

docs/docker.md
Even though I was following the official guide, I couldn't get verdaccio running. The problem was that SELinux was forbidding access to bind-mounted directories. For instance:
```
fatal--- cannot open config file /verdaccio/conf/config.yaml: Error: CONFIG: it does not look like a valid config file
```
In this PR I update the docs to make users aware of SELinux and help them solve denials related with bind-mounts. 
I believe some of the following issues could also be related to SELinux
https://github.com/verdaccio/verdaccio/issues/341
https://github.com/verdaccio/website/issues/233
https://github.com/verdaccio/docker-examples/issues/30
=> docs(website): SELinux troubleshooting

website/translated_docs/de/reverse-proxy.md
After run `nginx -t` with ssl configuration, this `warning` appears.
`nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in`
So I removed the line that contains `ssl on;` to fix this warning
=> Just a simple warning for nginx resolved

docs/packages.md
I made an issue yesterday about npm not working if access permissions of a package require the user to log in (https://github.com/verdaccio/verdaccio/discussions/2152). Apparently this was caused by npm not sending authentication headers with GET requests by default. I thought maybe this should be mentioned in the documentation of Verdaccio as well. Does this addition seem sensible?
=> Add note about npm not sending authentication data with GET requests

docs/kubernetes.md
It is now named existingConfigMap
I just ran:
git grep -l 'customConfigMap' | xargs sed -i 's/customConfigMap/existingConfigMap/g'
#361
=> Fix outdated kubernetes documentation for customConfigMap

docs/docker.md
Added a hint for docker users to create a `config.yaml` (when the conf folder is mapped to the host system) before they start the container. Otherwise not creating the config file will lead to parse problems and unstartable containers.
=> Updated docker docs
